[OpenRouter]

base_url = https://openrouter.ai/api/v1
openrouter_api_key = add your API key here

# Name of model to use when submitting request to OpenRouterAI
model = openai/gpt-4o-mini

# Model name to append to saved JSON file
model_file_inf = gpt-4o-mini


[DeepL]

deepl_API_key = add your API key here
source_lang = JA
target_lang = EN-US
model_type = prefer_quality_optimized